homework 2
================
Polly Wu (rw3031)
2024-09-24

# Problem 1

### import and tidy the NYC transit dataset

``` r
subway = 
  read_csv("./NYC_Transit_Subway_Entrance_And_Exit_Data.csv",  
           na = c("NA", ".",""))|>
  janitor::clean_names()|>
  select(line:entry, vending, ada)|>
  mutate(entry = recode(entry, "YES" = TRUE ,"NO" = FALSE))
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

### describe the dataset

The subway dataset contains variables including: line, station_name,
station_latitude, station_longitude, route1, route2, route3, route4,
route5, route6, route7, route8, route9, route10, route11, entrance_type,
entry, vending, ada.

For cleaning up the data, I convert the format of all of the column
names into lower case and connected through underscore. I have retain
the variables that we are interested in and convert the entry column
into a logical variable.

There are 19 columns and 1868 rows.

The data is not tidy since we still have the route column in wide
format.Each route is stored in a different column instead of
consolidated together.

``` r
station = distinct(subway,line,station_name, .keep_all = TRUE)
nrow(station)
```

    ## [1] 465

``` r
nrow(filter(station,ada == "TRUE"))
```

    ## [1] 84

``` r
nrow(filter(station,vending == "NO"))/nrow(station)*100
```

    ## [1] 1.935484

There are 465 distinct stations. 84 stations are ADA compliant. 1.94% of
the stations entrance/exit are without vending allow entrance.

### tidy up the route variable

``` r
subway =
  subway|>
  mutate(route8 = as.character(route8),
         route9 = as.character(route9),
         route10 = as.character(route10),
         route11 = as.character(route11),)|>
  pivot_longer(
    route1:route11,
    names_to = "route_no",
    names_prefix = "route",
    values_to = "route_name"
  )
```

### A_train stations

``` r
station = distinct(subway,line,station_name, .keep_all = TRUE)
nrow(filter(station,route_name == "A"))
```

    ## [1] 60

``` r
nrow(filter(station,route_name =="A", ada == "TRUE"))
```

    ## [1] 17

There are 60 distinct stations serve the A train and 17 of them are ADA
compliance.

# Problem 2

### import the trash-wheel dataset

``` r
mr_trash = 
  read_excel("./202309 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", skip = 1,  na = c("NA", ".","")) |>
  janitor::clean_names()|>
  select(dumpster, weight_tons:homes_powered)|>
  mutate(sports_balls=as.integer(sports_balls), type = "mr.")
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
professor_trash = 
  read_excel("./202309 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", skip = 1,  na = c("NA", ".","")) |>
  janitor::clean_names()|>
  select(dumpster, weight_tons:homes_powered)|>
  mutate(type = "professor")
```

``` r
Gwynnda = 
  read_excel("./202309 Trash Wheel Collection Data.xlsx", sheet = "Gwynnda Trash Wheel", skip = 1,  na = c("NA", ".","")) |>
  janitor::clean_names()|>
  select(dumpster, weight_tons:homes_powered)|>
  mutate(type = "gwynnda")
```

### merge the three datasets

``` r
trash_wheel = 
  bind_rows(mr_trash, professor_trash, Gwynnda)
```

The merged trash_wheel dataset has the follow variables dumpster,
weight_tons, volume_cubic_yards, plastic_bottles, polystyrene,
cigarette_butts, glass_bottles, plastic_bags, wrappers, sports_balls,
homes_powered, type. There are 849observations and 12 variables. \`

# Problem 3
